name: cash-tool
version: '0.1.0.0'
category: Web
author: Author name here
maintainer: example@example.com
copyright: 2017 Author name here
license: BSD3
github: runeksvendsen/cash-tool

extra-source-files:
- README.md

library:
  source-dirs: src
  exposed-modules:
  - Lib
  dependencies:
  - base >=4.7 && <5
  - cereal
  - base16-bytestring
  - haskoin-core
  - bytestring
  - http-types
  - optparse-generic
  - http-client
  - http-client-tls
  - servant-client
  - string-conversions
  - blockchain-restful-address-index-api
  - aeson
  - retry

executables:
  cash-tool:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - cash-tool

tests:
  cash-tool-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - cash-tool
    - hspec
    - QuickCheck
