resolver: lts-8.24

packages:
- .
- location:
    git: https://github.com/runeksvendsen/blockchain-restful-address-index-api.git
    commit: faf80b88702069a905218b3bb07b3aada3c52f17
  extra-dep: true

extra-deps:
- haskoin-core-0.4.2
- murmur3-1.0.3
- pbkdf-1.1.1.1
- secp256k1-0.4.8

flags: {}
extra-package-dbs: []
